[package]
name = "inquint-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "CLI for the inquint explicit-state model checker"

[[bin]]
name = "inquint"
path = "src/main.rs"

[dependencies]
quint-ast = { path = "../quint-ast" }
inquint = { path = "../inquint" }
clap = { workspace = true }
serde_json = { workspace = true }
